import { useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { AlertCircle, Plus } from "lucide-react";

interface DateRangeDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function DateRangeDialog({ open, onOpenChange }: DateRangeDialogProps) {
  const [fromDate, setFromDate] = useState("");
  const [toDate, setToDate] = useState("");

  const handleCreate = () => {
    console.log("Create report for date range:", { fromDate, toDate });
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[380px] bg-zinc-900 border-amber-500/20">
        <DialogHeader>
          <DialogTitle className="text-center text-lg font-bold">Input Criteria</DialogTitle>
        </DialogHeader>
        
        <div className="bg-amber-500/10 border border-amber-500/30 rounded-md p-3 flex items-start gap-2">
          <AlertCircle className="w-4 h-4 text-amber-500 mt-0.5 flex-shrink-0" />
          <p className="text-xs text-amber-500">
            Information generated by live API; do not spam requests
          </p>
        </div>

        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="from-date" className="text-sm font-medium text-white">
              From...
            </Label>
            <Input
              id="from-date"
              data-testid="input-from-date"
              type="datetime-local"
              value={fromDate}
              onChange={(e) => setFromDate(e.target.value)}
              className="bg-zinc-800 border-zinc-700 text-white"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="to-date" className="text-sm font-medium text-white">
              To...
            </Label>
            <Input
              id="to-date"
              data-testid="input-to-date"
              type="datetime-local"
              value={toDate}
              onChange={(e) => setToDate(e.target.value)}
              className="bg-zinc-800 border-zinc-700 text-white"
            />
          </div>

          <Button
            data-testid="button-create-range"
            onClick={handleCreate}
            disabled={!fromDate || !toDate}
            className="w-full bg-green-600 hover:bg-green-700 text-white"
          >
            <Plus className="w-4 h-4 mr-2" />
            Create
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
