import { useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { AlertCircle, Download } from "lucide-react";

interface ModerationReportDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function ModerationReportDialog({ open, onOpenChange }: ModerationReportDialogProps) {
  const [robloxId, setRobloxId] = useState("");
  const [discordId, setDiscordId] = useState("");

  const handlePreview = () => {
    console.log("Preview report for:", { robloxId, discordId });
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[400px] bg-zinc-900 border-amber-500/20">
        <DialogHeader>
          <DialogTitle className="text-center text-lg font-bold">User Moderations Report</DialogTitle>
        </DialogHeader>
        
        <div className="bg-amber-500/10 border border-amber-500/30 rounded-md p-3 flex items-start gap-2">
          <AlertCircle className="w-4 h-4 text-amber-500 mt-0.5 flex-shrink-0" />
          <p className="text-xs text-amber-500">
            Information generated by live API; do not spam requests
          </p>
        </div>

        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="roblox-id" className="text-sm font-medium text-white">
              User Roblox ID
            </Label>
            <Input
              id="roblox-id"
              data-testid="input-roblox-id"
              placeholder="Enter a valid Roblox ID"
              value={robloxId}
              onChange={(e) => setRobloxId(e.target.value)}
              className="bg-zinc-800 border-zinc-700 text-white"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="discord-id-report" className="text-sm font-medium text-white">
              User Discord ID
            </Label>
            <Input
              id="discord-id-report"
              data-testid="input-discord-id-report"
              placeholder="Enter a valid Discord ID"
              value={discordId}
              onChange={(e) => setDiscordId(e.target.value)}
              className="bg-zinc-800 border-zinc-700 text-white"
            />
          </div>

          <div className="flex gap-2">
            <Button
              data-testid="button-preview"
              onClick={handlePreview}
              disabled={!robloxId.trim() && !discordId.trim()}
              className="flex-1 bg-green-600 hover:bg-green-700 text-white"
            >
              <Download className="w-4 h-4 mr-2" />
              Preview
            </Button>
            <Button
              data-testid="button-cancel-report"
              onClick={() => {
                setRobloxId("");
                setDiscordId("");
                onOpenChange(false);
              }}
              variant="destructive"
              className="flex-1"
            >
              Cancel
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
