import { useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { AlertCircle } from "lucide-react";
import { useQuery } from "@tanstack/react-query";

interface UserLookupDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

interface DiscordUser {
  username: string;
  id: string;
}

export function UserLookupDialog({ open, onOpenChange }: UserLookupDialogProps) {
  const [discordId, setDiscordId] = useState("");
  const [searchId, setSearchId] = useState<string | null>(null);

  const { data: userData, isLoading } = useQuery<DiscordUser>({
    queryKey: ["/api/discord/lookup", searchId],
    enabled: !!searchId,
  });

  const handleLookup = () => {
    if (discordId.trim()) {
      setSearchId(discordId.trim());
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[400px] bg-zinc-900 border-amber-500/20">
        <DialogHeader>
          <DialogTitle className="text-center text-lg font-bold">User Lookup</DialogTitle>
        </DialogHeader>
        
        <div className="bg-amber-500/10 border border-amber-500/30 rounded-md p-3 flex items-start gap-2">
          <AlertCircle className="w-4 h-4 text-amber-500 mt-0.5 flex-shrink-0" />
          <p className="text-xs text-amber-500">
            Information generated by live API; do not spam requests
          </p>
        </div>

        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="discord-id" className="text-sm font-medium text-white">
              Discord ID
            </Label>
            <Input
              id="discord-id"
              data-testid="input-discord-id"
              placeholder="Enter a valid Discord ID"
              value={discordId}
              onChange={(e) => setDiscordId(e.target.value)}
              className="bg-zinc-800 border-zinc-700 text-white"
            />
          </div>

          {searchId && userData && (
            <div className="space-y-2 p-4 bg-zinc-800 rounded-md border border-zinc-700">
              <div className="space-y-1">
                <p className="text-xs text-zinc-400">User Information</p>
                <p className="text-sm text-white">{userData.username || "Unknown User"}</p>
              </div>
            </div>
          )}

          <div className="flex gap-2">
            <Button
              data-testid="button-search"
              onClick={handleLookup}
              disabled={!discordId.trim() || isLoading}
              className="flex-1 bg-green-600 hover:bg-green-700 text-white"
            >
              Search
            </Button>
            <Button
              data-testid="button-cancel"
              onClick={() => {
                setDiscordId("");
                setSearchId(null);
                onOpenChange(false);
              }}
              variant="destructive"
              className="flex-1"
            >
              Cancel
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
